format = "[](color_orange)$username[](bg:color_yellow fg:color_orange)$directory[](fg:color_yellow bg:color_aqua)$git_branch$git_status[](fg:color_aqua bg:color_blue)$c$rust$golang$nodejs$php$java$kotlin$haskell$python[](fg:color_blue bg:color_bg3)$docker_context$conda[](fg:color_bg3 bg:color_bg1)$time[ ](fg:color_bg1)$line_break$character"
palette = "catppuccin-mocha"

[c]
format = "[[ $symbol( $version) ](fg:color_bg1 bg:color_blue)]($style)"
style = "bg:color_blue"
symbol = " "

[character]
disabled = false
error_symbol = "[](bold fg:color_red)"
success_symbol = "[](bold fg:color_green)"
vimcmd_replace_one_symbol = "[](bold fg:color_purple)"
vimcmd_replace_symbol = "[](bold fg:color_purple)"
vimcmd_symbol = "[](bold fg:color_green)"
vimcmd_visual_symbol = "[](bold fg:color_yellow)"

[conda]
format = "[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)"
style = "bg:color_bg3"

[directory]
format = "[ $path ]($style)"
style = "fg:color_bg1 bg:color_yellow"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Developer = "󰲋 "
Documents = "󰈙 "
Downloads = " "
Music = "󰝚 "
Pictures = " "

[docker_context]
format = "[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)"
style = "bg:color_bg3"
symbol = ""

[git_branch]
format = "[[ $symbol $branch ](fg:color_bg1 bg:color_aqua)]($style)"
style = "bg:color_aqua"
symbol = ""

[git_status]
format = "[[($all_status$ahead_behind )](fg:color_bg1 bg:color_aqua)]($style)"
style = "bg:color_aqua"

[golang]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)"
style = "bg:color_blue"
symbol = ""

[haskell]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)"
style = "bg:color_blue"
symbol = ""

[java]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)"
style = "bg:color_blue"
symbol = " "

[kotlin]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)"
style = "bg:color_blue"
symbol = ""

[line_break]
disabled = false

[nodejs]
format = "[[ $symbol( $version) ](fg:color_bg1 bg:color_blue)]($style)"
style = "bg:color_blue"
symbol = ""

[os]
disabled = false
style = "bg:color_orange fg:color_bg1"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
Raspbian = "󰐿"
RedHatEnterprise = "󱄛"
Redhat = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"

[palettes]
[palettes.catppuccin-macchiato]
color_aqua = "#91d7e3"
color_bg1 = "#1e2030"
color_bg3 = "#24273a"
color_blue = "#8aadf4"
color_fg0 = "#cad3f5"
color_green = "#a6da95"
color_orange = "#f5a97f"
color_purple = "#c6a0f6"
color_red = "#ed8796"
color_yellow = "#eed49f"

[palettes.catppuccin-mocha]
color_aqua = "#89dceb"
color_bg1 = "#181825"
color_bg3 = "#1e1e2e"
color_blue = "#89b4fa"
color_fg0 = "#cdd6f4"
color_green = "#a6e3a1"
color_orange = "#fab387"
color_purple = "#b4befe"
color_red = "#f38ba8"
color_yellow = "#f9e2af"

[php]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)"
style = "bg:color_blue"
symbol = ""

[python]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)"
style = "bg:color_blue"
symbol = ""

[rust]
format = "[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)"
style = "bg:color_blue"
symbol = ""

[time]
disabled = false
format = "[[  $time ](fg:color_fg0 bg:color_bg1)]($style)"
style = "bg:color_bg1"
time_format = "%R"

[username]
format = "[ $user ]($style)"
show_always = true
style_root = "bg:color_orange fg:color_bg1"
style_user = "bg:color_orange fg:color_bg1"
